services:

  database:
    image: mysql:8.0.32
    container_name: agrix_db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: agrix_db
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ] # Deve aguardar o banco ficar operacional
      timeout: 10s
      retries: 5
  
  backend:
    build: .
    container_name: agrix_api
    restart: always
    ports:
      - 8080:8080
    links:
      - database:agrix_db # acessa database pelo hostname (agrix_db)
    environment:
      - DATABASE_HOST=agrix_db
      - DATABASE_PORT=3306
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=agrix_db

    depends_on:
      database:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "lsof", "-t", "-i:8080" ]
      timeout: 10s
      retries: 5